CREATE TABLE ORDERS (
ORDER_ID VARCHAR(20) NOT NULL,
STATUS VARCHAR(10) NOT NULL,
FAIL_REASON VARCHAR(30),
RETURN_STATUS VARCHAR(10),
CUSTOMER_ID VARCHAR(50),
EFFDT DATETIME,
PRODUCT_GROSS DOUBLE,
CUSTOMER_SHIP_FEE DOUBLE,
SHOPEE_SHIP_FEE DOUBLE,
RETURN_SHIP_FEE DOUBLE,
TOTAL_PAID DOUBLE,
SHOPEE_SUBSIDY DOUBLE,
SHOPEE_REDEEM DOUBLE,
CREDIT_DISCOUNT DOUBLE,
DISCOUNT_CODE VARCHAR(50),
CUSTOMER_COUPON DOUBLE,
CUSTOMER_GIVEBACK DOUBLE,
SHOPEE_COUPON DOUBLE,
TRANSCATION_FEE DOUBLE,
SERVICE_FEE DOUBLE,
CASHFLOW_FEE DOUBLE,
INSTALLMENTS INT,
CREDIT_CHARGE VARCHAR(20),
MAIN_COMMODITY_NM VARCHAR(100),
SUB_COMMODITY_NM VARCHAR(100),
ORG_PRICE DOUBLE ,
DIS_PRICE DOUBLE,
MAIN_COMMODITY_ID VARCHAR(50),
SUB_COMMODITY_ID VARCHAR(50),
COUNT INT,
PROMOTION_METRIC VARCHAR(10),
SHOPEE_PROMOTION VARCHAR(50),
RECIPIENT_ADDR VARCHAR(100),
RECIPIENT_PHONE VARCHAR(20),
PICKUP_STORE_ID VARCHAR(20),
CITY VARCHAR(50),
DISTRICT VARCHAR(50),
POSTAL VARCHAR(10),
RECIPIENT_NAME VARCHAR(50),
SHIPPING_TYPE VARCHAR(20),
DELIVER_TYPE VARCHAR(20),
PREPARE_TIME VARCHAR(100),
PAYMENT_TYPE VARCHAR(20),
LAST_SHIP_TIME DATETIME,
SHIIPPING_CODE VARCHAR(30),
CUSTOMER_PAID_TIME DATETIME,
ACTUAL_SHIP_TIME DATETIME,
ORDER_COMPLETE_TIME DATETIME,
CUSTOMER_COMMENT LONGTEXT,
COMMENT LONGTEXT,
CONSTRAINT PK_ORDERS PRIMARY KEY (ORDER_ID,STATUS,FAIL_REASON,RETURN_STATUS,CUSTOMER_ID,EFFDT,MAIN_COMMODITY_NM,SUB_COMMODITY_NM)
);
COMMIT;
DROP TABLE ORDERS;

ALTER TABLE AWS_FLORINE_DEV.ORDERS DROP PRIMARY KEY;
ALTER TABLE ORDERS DROP PRIMARY KEY;

ALTER TABLE ORDERS
ADD CONSTRAINT PK_ORDERS PRIMARY KEY (ORDER_ID,STATUS,FAIL_REASON,RETURN_STATUS,CUSTOMER_ID,EFFDT,MAIN_COMMODITY_NM,SUB_COMMODITY_NM);

CREATE DATABASE AWS_FLORINE_DEV;

SELECT * FROM ORDERS;

ALTER TABLE ORDERS
MODIFY COLUMN FAIL_REASON VARCHAR(100);


 SELECT SUM(A.SUB_SUM) FROM 
(SELECT  ORDER_ID,SUM(COUNT) as SUB_SUM FROM ORDERS WHERE STATUS <>N'不成立' AND COUNT<10  GROUP BY ORDER_ID) A;


SHOW VARIABLES LIKE '%ssl%';