# Generated by Django 3.2.15 on 2022-10-05 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ACTUAL_PROFIT',
            fields=[
                ('ORDER_ID', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('STATUS', models.CharField(max_length=20)),
                ('EFFDT', models.DateTimeField(auto_now=True)),
                ('YYYYMM', models.CharField(max_length=10)),
                ('PRODUCT_GROSS', models.IntegerField(default=0)),
                ('ACTUAL_PROFIT', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'ACTUAL_PROFIT',
            },
        ),
        migrations.CreateModel(
            name='ALL_PROFIT_VW',
            fields=[
                ('YYYYMM', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('NUMYYYYMM', models.IntegerField(default=0)),
                ('PROFIT', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'ALL_PROFIT_VW',
            },
        ),
        migrations.CreateModel(
            name='COST',
            fields=[
                ('COST', models.IntegerField(default=0, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'COST',
            },
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=10)),
                ('quantity', models.IntegerField(default=0)),
                ('pub_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HotSales',
            fields=[
                ('MAIN_COMMODITY_NM', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('SUMP', models.IntegerField(default=0)),
                ('SUMC', models.IntegerField(default=0)),
                ('PERCENT', models.FloatField(default=0)),
            ],
            options={
                'db_table': 'test',
            },
        ),
        migrations.CreateModel(
            name='MONTH_REVENUE',
            fields=[
                ('YYYYMM', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('NUMYYYYMM', models.IntegerField(default=0)),
                ('MONTH_REVENUE', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'MONTH_REVENUE',
            },
        ),
        migrations.CreateModel(
            name='SUM_ACTUAL_PROFIT',
            fields=[
                ('SUM_ACTUAL_PROFIT', models.IntegerField(default=0, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='SUM_TOTAL_PROFIT',
            fields=[
                ('SUM_TOTAL_PROFIT', models.IntegerField(default=0, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='TOTAL_ORDERS',
            fields=[
                ('COUNT', models.IntegerField(default=0, primary_key=True, serialize=False)),
            ],
        ),
    ]
