# Generated by Django 3.2.15 on 2022-12-02 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllORDERS',
            fields=[
                ('ORDER_ID', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('EFFDT', models.DateTimeField(auto_now=True)),
                ('STATUS', models.CharField(max_length=20)),
                ('COMMODITY_NM', models.CharField(max_length=256)),
                ('SHIIPPING_CODE', models.CharField(max_length=10)),
                ('SHIPPING_TYPE', models.CharField(max_length=20)),
                ('RECIPIENT_NAME', models.CharField(max_length=20)),
                ('PRODUCT_GROSS', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'AllORDERS',
            },
        ),
        migrations.CreateModel(
            name='GETYYYYMM',
            fields=[
                ('YYYYMM', models.IntegerField(default=0, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='GETYYYYMMDD',
            fields=[
                ('YYYYMMDD', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
    ]
