# Generated by Django 3.2.15 on 2022-12-02 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_allorders_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AllORDERS',
            new_name='ALLORDERSDJ',
        ),
    ]
